[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "0"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self'; 
    style-src 'self' 'unsafe-inline' cdn.jsdelivr.net https://fonts.googleapis.com *.netlify.app; 
    form-action 'self'; 
    font-src 'self' https://fonts.googleapis.com https://fonts.gstatic.com https://cdn.jsdelivr.net; 
    script-src 'self' 'unsafe-inline' *.googleapis.com cdn.jsdelivr.net *.netlify.app; 
    media-src 'self' https://www.youtube.com https://youtube.com;
    connect-src 'self'; 
    img-src 'self'; 
    base-uri 'self';"