name: Build Images Reference Docs

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

env:
  WORKDIR: reference
  CHANGELOG_FILE: changelog.md
  LAST_UPDATE_FILE: last-update.md

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out Destination Repo"
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
        with:
          path: edu

      - name: "Check out Images Monorepo"
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
        with:
          repository: chainguard-images/images
          path: images

      - name: "Set up workdir"
        run: |
          mkdir -p "${{ github.workspace }}/${{ env.WORKDIR }}" && \
          chmod 777 "${{ github.workspace }}/${{ env.WORKDIR }}"

      - name: "Update the reference docs for Chainguard Images"
        uses: chainguard-dev/deved-autodocs@1.3.7
        with:
          command: build images
        env:
          YAMLDOCS_SOURCE: "${{ github.workspace }}/images/images"
          YAMLDOCS_OUTPUT: "${{ github.workspace }}/${{ env.WORKDIR }}"
          YAMLDOCS_TEMPLATES: "${{ github.workspace }}/edu/autodocs/templates"
          YAMLDOCS_LAST_UPDATE: "${{ github.workspace }}/${{ env.WORKDIR }}/${{ env.LAST_UPDATE_FILE }}"
          YAMLDOCS_DIFF_SOURCE: "${{ github.workspace }}/edu/content/chainguard/chainguard-images/${{ env.WORKDIR }}"

      - name: "Copy changelog to autodocs folder"
        run: |
          mv "${{ github.workspace }}/${{ env.WORKDIR }}/${{ env.LAST_UPDATE_FILE }}" \
          "${{ github.workspace }}/edu/autodocs"

      - name: "Copy updates to main repo"
        run: |
          echo "Copying files..." && \
          cp -R "${{ github.workspace }}/${{ env.WORKDIR }}" "${{ github.workspace }}/edu/content/chainguard/chainguard-images" && \
          echo "Finished copy"

      - name: "Get Last Update"
        run: |
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "LAST_UPDATE<<$EOF" >> $GITHUB_ENV
          echo "`cat ${{ github.workspace }}/edu/autodocs/${{ env.LAST_UPDATE_FILE }}`" >> $GITHUB_ENV
          echo "$EOF" >> $GITHUB_ENV

      - name: "Get Changelog"
        run: |
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "CHANGELOG<<$EOF" >> $GITHUB_ENV
          echo "`cat ${{ github.workspace }}/edu/autodocs/${{ env.CHANGELOG_FILE }}`" >> $GITHUB_ENV
          echo "$EOF" >> $GITHUB_ENV

      - name: "Update Changelog"
        run: |
          [ ! -f "${{ github.workspace }}/edu/autodocs/${{ env.CHANGELOG_FILE }}" ] && touch ${{ github.workspace }}/edu/autodocs/${{ env.CHANGELOG_FILE }}
          cat ${{ env.LAST_UPDATE }} > ${{ github.workspace }}/edu/autodocs/${{ env.CHANGELOG_FILE }}
          echo "\n\n" >> ${{ github.workspace }}/edu/autodocs/${{ env.CHANGELOG_FILE }}
          cat ${{ env.CHANGELOG }} >> ${{ github.workspace }}/edu/autodocs/${{ env.CHANGELOG_FILE }}

      - name: Create a PR
        uses: peter-evans/create-pull-request@2b011faafdcbc9ceb11414d64d0573f37c774b04 # v4.2.3
        id: cpr
        with:
          path: "${{ github.workspace }}/edu"
          commit-message: Update Images Reference
          title: "[AutoDocs] Update Images Reference Docs"
          body: "${{ env.LAST_UPDATE }}"
          signoff: true
          labels: |
            documentation
            images
            automated
          assignees: erikaheidi

      - name: "Send notification to Slack"
        if: ${{ steps.cpr.outputs.pull-request-number }}
        uses: chainguard-dev/deved-autodocs@1.3.7
        with:
          command: notify pullrequest
        env:
          AUTODOCS_SLACK_PRIMARY: ${{ secrets.AUTODOCS_SLACK_PRIMARY }}
          AUTODOCS_SLACK_SECONDARY: ${{ secrets.AUTODOCS_SLACK_SECONDARY }}
          AUTODOCS_SLACK_GENERAL: ${{ secrets.AUTODOCS_SLACK_GENERAL }}
          PR_NUMBER: ${{ steps.cpr.outputs.pull-request-number }}
          PR_ACTION: ${{ steps.cpr.outputs.pull-request-operation }}
          PR_URL: ${{ steps.cpr.outputs.pull-request-url }}
          PR_SHA: ${{ steps.cpr.outputs.pull-request-head-sha }}
          PR_SUMMARY: ${{ env.LAST_UPDATE }}
